### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 테스트 제목
POST https://localhost:443/api/users/login
Accept: application/json
Content-Type: application/json; charset=UTF-8

{
  "loginId" : "id1111",
  "password" : "Qwer1111!"
}
> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}

### a
GET https://localhost:443/api/stores?page=0&size=5
Content-Type: application/json

### 테스트 제목
POST http://localhost:8080/api/users/login
Accept: application/json
Content-Type: application/json; charset=UTF-8

{
  "loginId" : "id1111",
  "password" : "Qwer1111!"
}
> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}
### 테스트 1
GET https://localhost:443/api/auth/test
Content-Type: application/json; charset=UTF-8

### 테스트 2
GET https://localhost:443/api/auth/test2
Content-Type: application/json; charset=UTF-8

### 테스트 3
GET https://localhost:443/api/auth/test3
Content-Type: application/json; charset=UTF-8

### 로그인 테스트
POST https://localhost:443/api/users/signup
Content-Type: application/json

{
  "loginId" : "id11111",
  "password" : "Qwer1111!",
  "name" : "킹원하",
  "nickname" : "King",
  "address" : "너의 맘속",
  "phone" : "01012341111",
  "email" : "email1@email.com",
  "intro" : "원하는 배고파요",
  "role" : "USER"
}




### 로그인 테스트
POST https://localhost:443/api/users/login
Content-Type: application/json
testAA: testcode112ffkkejfaleijfslekfjl

{
"loginId" : "id1111",
"password" : "Qwer1111!"
}
> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}

### 매장 등록
POST https://localhost:443/api/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDIyMjIiLCJhdXRoIjoiU0VMTEVSIiwiZXhwIjoxNzIwMDk5MzA5LCJpYXQiOjE3MjAwOTU3MDl9.8zRb0EqHnIz9HGjb1SGKJgQt9y_PjWNaKfJDdtRR-qI

{
  "storeId" : 1,
  "storeName" : "역전할머니맥주",
  "intro" : "할무니 맥주 부천소사본점",
  "dialNumber" : "0507-1351-0514"
}

### 좋아요 등록
POST https://localhost:443/api/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDExMTEiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTcyMDA5OTg1OSwiaWF0IjoxNzIwMDk2MjU5fQ.kxgmwURUCx9PnM35Tcrr3cDA2eCmX7EWvsOeTRGpgI4

{
    "userLikeType" : "STORE",
    "typeId" : 1
}

### 쿼리DSL test : 유저의 좋아요 누른 기록 모두 조회
GET https://localhost:443/api/like/get-user-like
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDExMTEiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTcyMDEwNDk1MCwiaWF0IjoxNzIwMTAxMzUwfQ.ZpYV9oGvks0cHyRrXAgOs4D5hX0bagKkisZ5lYFRxXg